-- Xóa bảng nếu đã tồn tại để dễ dàng chạy lại script
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE THANHLY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PHIEUTRANCC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CT_PHIEUNHAP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PHIEUNHAP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE NHACUNGCAP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VIPHAM CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PHIEUTRA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CT_PHIEUMUON CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PHIEUMUON CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE KHOSACH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LOSACH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SACH CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DANHMUC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DOCGIA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TAIKHOAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    MATK NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENDANGNHAP VARCHAR2(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR2(255) NOT NULL,
    SDT VARCHAR2(15),
    VAITRO VARCHAR2(20) CHECK (VAITRO IN ('Reader', 'Librarian', 'InventoryManager', 'Admin')),
    NGAYTAO DATE DEFAULT SYSDATE,
    NGAYHETHANTHE DATE,
    TRANGTHAI NUMBER(1) DEFAULT 1 CHECK (TRANGTHAI IN (0, 1)) -- 1: Active, 0: Inactive
);

-- Bảng DOCGIA
CREATE TABLE DOCGIA (
    MADOCGIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MATK NUMBER NOT NULL REFERENCES TAIKHOAN(MATK),
    TENDOCGIA VARCHAR2(100) NOT NULL,
    SDT VARCHAR2(15),
    GIOITINH VARCHAR2(10),
    NGAYSINH DATE,
    DIACHI VARCHAR2(255)
);

-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANHANVIEN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MATK NUMBER NOT NULL REFERENCES TAIKHOAN(MATK),
    TENNHANVIEN VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(10),
    SDT VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CATRUC VARCHAR2(50)
);

-- Bảng DANHMUC
CREATE TABLE DANHMUC (
    MADANHMUC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENTHELOAI VARCHAR2(100) NOT NULL,
    MOTA VARCHAR2(500)
);

-- Bảng SACH
CREATE TABLE SACH (
    MASACH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENSACH VARCHAR2(200) NOT NULL,
    TACGIA VARCHAR2(100),
    NXB VARCHAR2(100),
    NAMXB NUMBER(4),
    MADANHMUC NUMBER REFERENCES DANHMUC(MADANHMUC),
    TINHTRANG VARCHAR2(50) DEFAULT 'San sang' CHECK (TINHTRANG IN ('San sang', 'Da muon', 'Da thanh ly', 'Bao tri')),
    VITRIKE VARCHAR2(50),
    GIASACH NUMBER
);

-- Bảng LOSACH
CREATE TABLE LOSACH (
    MALO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MASACH NUMBER NOT NULL REFERENCES SACH(MASACH),
    MADANHMUC NUMBER REFERENCES DANHMUC(MADANHMUC),
    NGAYNHAP DATE DEFAULT SYSDATE,
    SOLUONGSANPHAM NUMBER DEFAULT 0
);

-- Bảng KHOSACH
CREATE TABLE KHOSACH (
    MAKHO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MASACH NUMBER NOT NULL REFERENCES SACH(MASACH) UNIQUE,
    SOLUONGKHADUNG NUMBER DEFAULT 0,
    DONVITINH VARCHAR2(20) DEFAULT 'Quyen'
);

-- Bảng PHIEUMUON
CREATE TABLE PHIEUMUON (
    MAPHIEUMUON NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MANHANVIEN NUMBER REFERENCES NHANVIEN(MANHANVIEN),
    MADOCGIA NUMBER NOT NULL REFERENCES DOCGIA(MADOCGIA),
    NGAYMUON DATE DEFAULT SYSDATE,
    NGAYHENTRA DATE,
    TIENDATCOC NUMBER DEFAULT 0,
    SOLUONGSACH NUMBER DEFAULT 0,
    GHICHU VARCHAR2(500)
);

-- Bảng CT_PHIEUMUON
CREATE TABLE CT_PHIEUMUON (
    MAPHIEUMUON NUMBER REFERENCES PHIEUMUON(MAPHIEUMUON),
    MASACH NUMBER REFERENCES SACH(MASACH),
    PRIMARY KEY (MAPHIEUMUON, MASACH)
);

-- Bảng PHIEUTRA
CREATE TABLE PHIEUTRA (
    MAPHIEUTRA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MAPHIEUMUON NUMBER NOT NULL REFERENCES PHIEUMUON(MAPHIEUMUON) UNIQUE,
    MANHANVIEN NUMBER REFERENCES NHANVIEN(MANHANVIEN),
    NGAYTHUCTRA DATE DEFAULT SYSDATE,
    TIENPHATQUAHAN NUMBER DEFAULT 0,
    TINHTRANGSACHKHITRA VARCHAR2(100)
);

-- Bảng VIPHAM
CREATE TABLE VIPHAM (
    MAVIPHAM NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MADOCGIA NUMBER NOT NULL REFERENCES DOCGIA(MADOCGIA),
    MAPHIEUTRA NUMBER REFERENCES PHIEUTRA(MAPHIEUTRA),
    LOAIVIPHAM VARCHAR2(100) NOT NULL,
    SOTIENPHAT NUMBER DEFAULT 0,
    TRANGTHAITHANHTOAN NUMBER(1) DEFAULT 0 -- 0: Chua thanh toan, 1: Da thanh toan
);

-- Bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MANCC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENNCC VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(100),
    SDT VARCHAR2(15),
    DIACHI VARCHAR2(255)
);

-- Bảng PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    MAPHIEUNHAP NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MANHANVIEN NUMBER REFERENCES NHANVIEN(MANHANVIEN),
    MANCC NUMBER REFERENCES NHACUNGCAP(MANCC),
    NGAYNHAP DATE DEFAULT SYSDATE,
    TONGTIEN NUMBER DEFAULT 0,
    GHICHU VARCHAR2(500)
);

-- Bảng CT_PHIEUNHAP
CREATE TABLE CT_PHIEUNHAP (
    MAPHIEUNHAP NUMBER REFERENCES PHIEUNHAP(MAPHIEUNHAP),
    MASACH NUMBER REFERENCES SACH(MASACH),
    MALO NUMBER REFERENCES LOSACH(MALO),
    DONVITINH VARCHAR2(20) DEFAULT 'Quyen',
    SOLUONG NUMBER DEFAULT 1,
    GIANHAP NUMBER DEFAULT 0,
    PRIMARY KEY (MAPHIEUNHAP, MASACH)
);

-- Bảng PHIEUTRANCC
CREATE TABLE PHIEUTRANCC (
    MAPHIEUTRANCC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MAPHIEUNHAP NUMBER NOT NULL REFERENCES PHIEUNHAP(MAPHIEUNHAP),
    MANHANVIEN NUMBER REFERENCES NHANVIEN(MANHANVIEN),
    NGAYTRA DATE DEFAULT SYSDATE,
    LYDOTRA VARCHAR2(500),
    MASACH NUMBER REFERENCES SACH(MASACH),
    SOLUONG NUMBER DEFAULT 1,
    DONGIATRA NUMBER DEFAULT 0,
    TONGTIEN NUMBER DEFAULT 0
);

-- Bảng THANHLY
CREATE TABLE THANHLY (
    MAPHIEUTHANHLY NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NGAYTHANHLY DATE DEFAULT SYSDATE,
    LYDO VARCHAR2(500),
    MASACH NUMBER REFERENCES SACH(MASACH),
    SOLUONG NUMBER DEFAULT 1,
    NGUOIPHEDUYET NUMBER REFERENCES NHANVIEN(MANHANVIEN)
);
