-- Script bổ sung cho đồ án HQTCSDL.
-- Mục tiêu: chuẩn hóa các giao tác mượn/trả sách để minh họa xử lý đồng thời trên Oracle.
-- Chạy sau Create_Tables.sql và các sequence/trigger cơ bản.

CREATE OR REPLACE FUNCTION FN_SO_LUONG_CON_LAI(P_EDITION_ID IN VARCHAR2)
RETURN NUMBER
IS
    V_COPIES NUMBER;
BEGIN
    SELECT NUM_OF_COPIES
    INTO V_COPIES
    FROM EDITION
    WHERE EDITION_ID = P_EDITION_ID;

    RETURN V_COPIES;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_SACH_DANG_MUON(P_USER_ID IN VARCHAR2)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM RENT_HISTORY
    WHERE USER_ID = P_USER_ID
      AND STATUS = 0;

    RETURN V_COUNT;
END;
/

CREATE OR REPLACE FUNCTION FN_TINH_TIEN_PHAT(P_RENT_HISTORY_ID IN VARCHAR2)
RETURN NUMBER
IS
    V_DAYS_OVERDUE NUMBER;
BEGIN
    SELECT GREATEST(TRUNC(SYSDATE) - TRUNC(RETURN_DATE), 0)
    INTO V_DAYS_OVERDUE
    FROM RENT_HISTORY
    WHERE RENT_HISTORY_ID = P_RENT_HISTORY_ID;

    RETURN V_DAYS_OVERDUE * 1000;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE PROCEDURE SP_DUYET_YEU_CAU_MUON(
    P_USER_ID      IN VARCHAR2,
    P_EDITION_ID   IN VARCHAR2,
    P_RETURN_DATE  IN DATE DEFAULT NULL
)
IS
    V_REQUEST_COUNT NUMBER;
    V_COPIES        NUMBER;
    V_RETURN_DATE   DATE;
BEGIN
    -- Khóa dòng EDITION để tránh Lost Update khi nhiều thủ thư duyệt cùng một bản sách.
    SELECT NUM_OF_COPIES
    INTO V_COPIES
    FROM EDITION
    WHERE EDITION_ID = P_EDITION_ID
    FOR UPDATE;

    SELECT COUNT(*)
    INTO V_REQUEST_COUNT
    FROM REQUEST
    WHERE USER_ID = P_USER_ID
      AND EDITION_ID = P_EDITION_ID;

    IF V_REQUEST_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Không tồn tại yêu cầu mượn sách.');
    END IF;

    IF V_COPIES <= 0 THEN
        RAISE_APPLICATION_ERROR(-20012, 'Sách đã hết bản có thể mượn.');
    END IF;

    IF FN_SO_SACH_DANG_MUON(P_USER_ID) >= 5 THEN
        RAISE_APPLICATION_ERROR(-20013, 'Độc giả đã đạt giới hạn số sách đang mượn.');
    END IF;

    V_RETURN_DATE := NVL(P_RETURN_DATE, SYSDATE + 7);

    INSERT INTO RENT_HISTORY(USER_ID, EDITION_ID, RENT_DATE, RETURN_DATE, STATUS)
    VALUES (P_USER_ID, P_EDITION_ID, SYSDATE, V_RETURN_DATE, 0);

    UPDATE EDITION
    SET NUM_OF_COPIES = NUM_OF_COPIES - 1
    WHERE EDITION_ID = P_EDITION_ID;

    DELETE FROM REQUEST
    WHERE USER_ID = P_USER_ID
      AND EDITION_ID = P_EDITION_ID;
END;
/

CREATE OR REPLACE PROCEDURE SP_TRA_SACH(
    P_USER_ID          IN VARCHAR2,
    P_RENT_HISTORY_ID  IN VARCHAR2,
    P_DA_THANH_TOAN    IN NUMBER DEFAULT 0
)
IS
    V_EDITION_ID       VARCHAR2(20);
    V_UNPAID_FINE      NUMBER;
    V_FINE_AMOUNT      NUMBER;
BEGIN
    -- Khóa phiếu mượn để tránh hai phiên trả cùng một phiếu.
    SELECT EDITION_ID
    INTO V_EDITION_ID
    FROM RENT_HISTORY
    WHERE RENT_HISTORY_ID = P_RENT_HISTORY_ID
      AND USER_ID = P_USER_ID
      AND STATUS = 0
    FOR UPDATE;

    V_FINE_AMOUNT := FN_TINH_TIEN_PHAT(P_RENT_HISTORY_ID);

    SELECT COUNT(*)
    INTO V_UNPAID_FINE
    FROM FINE_HISTORY
    WHERE RENT_HISTORY_ID = P_RENT_HISTORY_ID
      AND PAYMENT_DATE IS NULL;

    IF V_FINE_AMOUNT > 0 AND V_UNPAID_FINE = 0 THEN
        INSERT INTO FINE_HISTORY(RENT_HISTORY_ID, FEE_AMOUNT, START_DATE)
        VALUES (P_RENT_HISTORY_ID, V_FINE_AMOUNT, SYSDATE);
        V_UNPAID_FINE := 1;
    END IF;

    IF V_UNPAID_FINE > 0 AND P_DA_THANH_TOAN = 0 THEN
        RAISE_APPLICATION_ERROR(-20021, 'Độc giả phải thanh toán tiền phạt trước khi hoàn tất trả sách.');
    END IF;

    IF V_UNPAID_FINE > 0 AND P_DA_THANH_TOAN = 1 THEN
        UPDATE FINE_HISTORY
        SET PAYMENT_DATE = SYSDATE,
            FEE_AMOUNT = CASE WHEN FEE_AMOUNT = 0 THEN V_FINE_AMOUNT ELSE FEE_AMOUNT END
        WHERE RENT_HISTORY_ID = P_RENT_HISTORY_ID
          AND PAYMENT_DATE IS NULL;
    END IF;

    UPDATE RENT_HISTORY
    SET STATUS = 1,
        RETURN_DATE = SYSDATE
    WHERE RENT_HISTORY_ID = P_RENT_HISTORY_ID;

    -- Khóa dòng tồn kho trước khi cộng lại bản sách.
    UPDATE EDITION
    SET NUM_OF_COPIES = NUM_OF_COPIES + 1
    WHERE EDITION_ID = V_EDITION_ID;
END;
/

-- Wrapper giữ tương thích với backend hiện tại.
CREATE OR REPLACE PROCEDURE INSERT_RENT_HISTORY(
    A_USER_ID      IN VARCHAR2,
    A_EDITION_ID   IN VARCHAR2,
    A_RETURN_DATE  IN DATE
)
IS
BEGIN
    SP_DUYET_YEU_CAU_MUON(A_USER_ID, A_EDITION_ID, A_RETURN_DATE);
END;
/

-- Wrapper giữ tương thích với backend hiện tại.
CREATE OR REPLACE PROCEDURE EDIT_HISTORY(
    U_ID  IN VARCHAR2,
    A_ID  IN VARCHAR2,
    PAY   IN NUMBER
)
IS
BEGIN
    SP_TRA_SACH(U_ID, A_ID, PAY);
END;
/
