-- =============================================================
-- HQTCSDL - Schema Oracle đúng theo mô hình trong ĐỒ_ÁN_HQTCSDL.txt
-- Chủ đề: Hệ thống quản lý thư viện
-- Ghi chú: Script này độc lập với schema gốc của repo, dùng làm bản chuẩn cho đồ án.
-- =============================================================

-- Xóa bảng theo thứ tự phụ thuộc. Có thể bỏ qua lỗi nếu bảng chưa tồn tại.
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CT_PHIEUNHAP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CT_PHIEUMUON CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PHIEUTRA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VIPHAM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PHIEUNHAP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PHIEUTRANCC CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE THANHLY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PHIEUMUON CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE KHOSACH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LOSACH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SACH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DOANHMUC CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NHACUNGCAP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DOCGIA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TAIKHOAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE TAIKHOAN (
    MaTaiKhoan   VARCHAR2(20) PRIMARY KEY,
    TenDangNhap  VARCHAR2(50) NOT NULL UNIQUE,
    MatKhau      VARCHAR2(200) NOT NULL,
    VaiTro       VARCHAR2(20) NOT NULL,
    TrangThai    VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    NgayTao      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT CK_TAIKHOAN_VAITRO CHECK (VaiTro IN ('DOC_GIA', 'THU_THU', 'QUAN_LY', 'ADMIN')),
    CONSTRAINT CK_TAIKHOAN_TRANGTHAI CHECK (TrangThai IN ('HOAT_DONG', 'KHOA'))
);

CREATE TABLE DOCGIA (
    MaDocGia     VARCHAR2(20) PRIMARY KEY,
    MaTaiKhoan   VARCHAR2(20) UNIQUE,
    HoTen        VARCHAR2(100) NOT NULL,
    Email        VARCHAR2(100) UNIQUE,
    SoDienThoai  VARCHAR2(20),
    DiaChi       VARCHAR2(200),
    NgayDangKy   DATE DEFAULT SYSDATE NOT NULL,
    NgayHetHan   DATE,
    TrangThai    VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT FK_DOCGIA_TAIKHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES TAIKHOAN(MaTaiKhoan),
    CONSTRAINT CK_DOCGIA_TRANGTHAI CHECK (TrangThai IN ('HOAT_DONG', 'KHOA', 'HET_HAN'))
);

CREATE TABLE NHANVIEN (
    MaNhanVien   VARCHAR2(20) PRIMARY KEY,
    MaTaiKhoan   VARCHAR2(20) UNIQUE,
    HoTen        VARCHAR2(100) NOT NULL,
    ChucVu       VARCHAR2(50) NOT NULL,
    Email        VARCHAR2(100) UNIQUE,
    SoDienThoai  VARCHAR2(20),
    TrangThai    VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT FK_NHANVIEN_TAIKHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES TAIKHOAN(MaTaiKhoan),
    CONSTRAINT CK_NHANVIEN_TRANGTHAI CHECK (TrangThai IN ('HOAT_DONG', 'NGHI_VIEC'))
);

CREATE TABLE DOANHMUC (
    MaDoanhMuc   VARCHAR2(20) PRIMARY KEY,
    TenDoanhMuc  VARCHAR2(100) NOT NULL UNIQUE,
    MoTa         VARCHAR2(500)
);

CREATE TABLE NHACUNGCAP (
    MaNhaCungCap VARCHAR2(20) PRIMARY KEY,
    TenNhaCungCap VARCHAR2(150) NOT NULL,
    DiaChi       VARCHAR2(200),
    Email        VARCHAR2(100),
    SoDienThoai  VARCHAR2(20)
);

CREATE TABLE SACH (
    MaSach       VARCHAR2(20) PRIMARY KEY,
    ISBN         VARCHAR2(20) UNIQUE,
    TenSach      VARCHAR2(200) NOT NULL,
    TacGia       VARCHAR2(200),
    NhaXuatBan   VARCHAR2(150),
    NamXuatBan   NUMBER(4),
    MaDoanhMuc   VARCHAR2(20),
    MoTa         VARCHAR2(1000),
    TrangThai    VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT FK_SACH_DOANHMUC FOREIGN KEY (MaDoanhMuc) REFERENCES DOANHMUC(MaDoanhMuc),
    CONSTRAINT CK_SACH_TRANGTHAI CHECK (TrangThai IN ('HOAT_DONG', 'NGUNG_LUU_THONG'))
);

CREATE TABLE LOSACH (
    MaLoSach     VARCHAR2(20) PRIMARY KEY,
    MaSach       VARCHAR2(20) NOT NULL,
    MaNhaCungCap VARCHAR2(20),
    NgayNhap     DATE DEFAULT SYSDATE NOT NULL,
    DonGia       NUMBER(12,2) DEFAULT 0 NOT NULL,
    SoLuongNhap  NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_LOSACH_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach),
    CONSTRAINT FK_LOSACH_NCC FOREIGN KEY (MaNhaCungCap) REFERENCES NHACUNGCAP(MaNhaCungCap),
    CONSTRAINT CK_LOSACH_SOLUONG CHECK (SoLuongNhap >= 0),
    CONSTRAINT CK_LOSACH_DONGIA CHECK (DonGia >= 0)
);

CREATE TABLE KHOSACH (
    MaKhoSach    VARCHAR2(20) PRIMARY KEY,
    MaSach       VARCHAR2(20) NOT NULL,
    ViTriKe      VARCHAR2(50),
    ViTriNgan    VARCHAR2(50),
    SoLuongTong  NUMBER DEFAULT 0 NOT NULL,
    SoLuongCon   NUMBER DEFAULT 0 NOT NULL,
    SoLuongHong  NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_KHOSACH_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach),
    CONSTRAINT UQ_KHOSACH_SACH UNIQUE (MaSach),
    CONSTRAINT CK_KHOSACH_SOLUONG CHECK (SoLuongTong >= 0 AND SoLuongCon >= 0 AND SoLuongHong >= 0 AND SoLuongCon <= SoLuongTong)
);

CREATE TABLE PHIEUMUON (
    MaPhieuMuon  VARCHAR2(20) PRIMARY KEY,
    MaDocGia     VARCHAR2(20) NOT NULL,
    MaNhanVien   VARCHAR2(20) NOT NULL,
    NgayMuon     DATE DEFAULT SYSDATE NOT NULL,
    NgayHenTra   DATE NOT NULL,
    TrangThai    VARCHAR2(20) DEFAULT 'DANG_MUON' NOT NULL,
    CONSTRAINT FK_PM_DOCGIA FOREIGN KEY (MaDocGia) REFERENCES DOCGIA(MaDocGia),
    CONSTRAINT FK_PM_NHANVIEN FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien),
    CONSTRAINT CK_PM_TRANGTHAI CHECK (TrangThai IN ('DANG_MUON', 'DA_TRA', 'QUA_HAN', 'HUY')),
    CONSTRAINT CK_PM_NGAY CHECK (NgayHenTra >= NgayMuon)
);

CREATE TABLE CT_PHIEUMUON (
    MaPhieuMuon  VARCHAR2(20) NOT NULL,
    MaSach       VARCHAR2(20) NOT NULL,
    SoLuong      NUMBER DEFAULT 1 NOT NULL,
    TrangThai    VARCHAR2(20) DEFAULT 'DANG_MUON' NOT NULL,
    PRIMARY KEY (MaPhieuMuon, MaSach),
    CONSTRAINT FK_CTPM_PM FOREIGN KEY (MaPhieuMuon) REFERENCES PHIEUMUON(MaPhieuMuon),
    CONSTRAINT FK_CTPM_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach),
    CONSTRAINT CK_CTPM_SOLUONG CHECK (SoLuong > 0),
    CONSTRAINT CK_CTPM_TRANGTHAI CHECK (TrangThai IN ('DANG_MUON', 'DA_TRA', 'MAT', 'HU_HONG'))
);

CREATE TABLE PHIEUTRA (
    MaPhieuTra   VARCHAR2(20) PRIMARY KEY,
    MaPhieuMuon  VARCHAR2(20) NOT NULL,
    MaNhanVien   VARCHAR2(20) NOT NULL,
    NgayTra      DATE DEFAULT SYSDATE NOT NULL,
    GhiChu       VARCHAR2(500),
    CONSTRAINT FK_PT_PM FOREIGN KEY (MaPhieuMuon) REFERENCES PHIEUMUON(MaPhieuMuon),
    CONSTRAINT FK_PT_NHANVIEN FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien)
);

CREATE TABLE VIPHAM (
    MaViPham     VARCHAR2(20) PRIMARY KEY,
    MaPhieuMuon  VARCHAR2(20) NOT NULL,
    LoaiViPham   VARCHAR2(30) NOT NULL,
    TienPhat     NUMBER(12,2) DEFAULT 0 NOT NULL,
    TrangThai    VARCHAR2(20) DEFAULT 'CHUA_THANH_TOAN' NOT NULL,
    NgayGhiNhan  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_VP_PM FOREIGN KEY (MaPhieuMuon) REFERENCES PHIEUMUON(MaPhieuMuon),
    CONSTRAINT CK_VP_LOAI CHECK (LoaiViPham IN ('QUA_HAN', 'HU_HONG', 'MAT_SACH')),
    CONSTRAINT CK_VP_TIEN CHECK (TienPhat >= 0),
    CONSTRAINT CK_VP_TRANGTHAI CHECK (TrangThai IN ('CHUA_THANH_TOAN', 'DA_THANH_TOAN'))
);

CREATE TABLE PHIEUNHAP (
    MaPhieuNhap  VARCHAR2(20) PRIMARY KEY,
    MaNhaCungCap VARCHAR2(20) NOT NULL,
    MaNhanVien   VARCHAR2(20) NOT NULL,
    NgayNhap     DATE DEFAULT SYSDATE NOT NULL,
    TongTien     NUMBER(12,2) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNhaCungCap) REFERENCES NHACUNGCAP(MaNhaCungCap),
    CONSTRAINT FK_PN_NHANVIEN FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien),
    CONSTRAINT CK_PN_TONGTIEN CHECK (TongTien >= 0)
);

CREATE TABLE CT_PHIEUNHAP (
    MaPhieuNhap  VARCHAR2(20) NOT NULL,
    MaSach       VARCHAR2(20) NOT NULL,
    SoLuong      NUMBER NOT NULL,
    DonGia       NUMBER(12,2) NOT NULL,
    PRIMARY KEY (MaPhieuNhap, MaSach),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAP(MaPhieuNhap),
    CONSTRAINT FK_CTPN_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach),
    CONSTRAINT CK_CTPN_SOLUONG CHECK (SoLuong > 0),
    CONSTRAINT CK_CTPN_DONGIA CHECK (DonGia >= 0)
);

CREATE TABLE PHIEUTRANCC (
    MaPhieuTraNCC VARCHAR2(20) PRIMARY KEY,
    MaNhaCungCap  VARCHAR2(20) NOT NULL,
    MaNhanVien    VARCHAR2(20) NOT NULL,
    NgayTra       DATE DEFAULT SYSDATE NOT NULL,
    LyDo          VARCHAR2(500),
    CONSTRAINT FK_PTNCC_NCC FOREIGN KEY (MaNhaCungCap) REFERENCES NHACUNGCAP(MaNhaCungCap),
    CONSTRAINT FK_PTNCC_NV FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien)
);

CREATE TABLE THANHLY (
    MaThanhLy    VARCHAR2(20) PRIMARY KEY,
    MaSach       VARCHAR2(20) NOT NULL,
    MaNhanVien   VARCHAR2(20) NOT NULL,
    SoLuong      NUMBER NOT NULL,
    LyDo         VARCHAR2(500),
    NgayThanhLy  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_TL_SACH FOREIGN KEY (MaSach) REFERENCES SACH(MaSach),
    CONSTRAINT FK_TL_NV FOREIGN KEY (MaNhanVien) REFERENCES NHANVIEN(MaNhanVien),
    CONSTRAINT CK_TL_SOLUONG CHECK (SoLuong > 0)
);
