-- =============================================================
-- HQTCSDL - Sequence, Trigger, Function, Procedure
-- Bám theo mô hình trong 01_HQTCSDL_Schema.sql
-- =============================================================

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TAIKHOAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DOCGIA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NHANVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DOANHMUC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NCC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SACH'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOSACH'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_KHOSACH'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PTNCC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE SEQ_TAIKHOAN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOCGIA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NHANVIEN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DOANHMUC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NCC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SACH START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOSACH START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_KHOSACH START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PM START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PN START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PTNCC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TL START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_TAIKHOAN_ID
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    IF :NEW.MaTaiKhoan IS NULL THEN
        :NEW.MaTaiKhoan := 'TK' || LPAD(SEQ_TAIKHOAN.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DOCGIA_ID
BEFORE INSERT ON DOCGIA
FOR EACH ROW
BEGIN
    IF :NEW.MaDocGia IS NULL THEN
        :NEW.MaDocGia := 'DG' || LPAD(SEQ_DOCGIA.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_NHANVIEN_ID
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaNhanVien IS NULL THEN
        :NEW.MaNhanVien := 'NV' || LPAD(SEQ_NHANVIEN.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DOANHMUC_ID
BEFORE INSERT ON DOANHMUC
FOR EACH ROW
BEGIN
    IF :NEW.MaDoanhMuc IS NULL THEN
        :NEW.MaDoanhMuc := 'DM' || LPAD(SEQ_DOANHMUC.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_NCC_ID
BEFORE INSERT ON NHACUNGCAP
FOR EACH ROW
BEGIN
    IF :NEW.MaNhaCungCap IS NULL THEN
        :NEW.MaNhaCungCap := 'NCC' || LPAD(SEQ_NCC.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SACH_ID
BEFORE INSERT ON SACH
FOR EACH ROW
BEGIN
    IF :NEW.MaSach IS NULL THEN
        :NEW.MaSach := 'S' || LPAD(SEQ_SACH.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOSACH_ID
BEFORE INSERT ON LOSACH
FOR EACH ROW
BEGIN
    IF :NEW.MaLoSach IS NULL THEN
        :NEW.MaLoSach := 'LS' || LPAD(SEQ_LOSACH.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_KHOSACH_ID
BEFORE INSERT ON KHOSACH
FOR EACH ROW
BEGIN
    IF :NEW.MaKhoSach IS NULL THEN
        :NEW.MaKhoSach := 'KS' || LPAD(SEQ_KHOSACH.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PM_ID
BEFORE INSERT ON PHIEUMUON
FOR EACH ROW
BEGIN
    IF :NEW.MaPhieuMuon IS NULL THEN
        :NEW.MaPhieuMuon := 'PM' || LPAD(SEQ_PM.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PT_ID
BEFORE INSERT ON PHIEUTRA
FOR EACH ROW
BEGIN
    IF :NEW.MaPhieuTra IS NULL THEN
        :NEW.MaPhieuTra := 'PT' || LPAD(SEQ_PT.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_VP_ID
BEFORE INSERT ON VIPHAM
FOR EACH ROW
BEGIN
    IF :NEW.MaViPham IS NULL THEN
        :NEW.MaViPham := 'VP' || LPAD(SEQ_VP.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PN_ID
BEFORE INSERT ON PHIEUNHAP
FOR EACH ROW
BEGIN
    IF :NEW.MaPhieuNhap IS NULL THEN
        :NEW.MaPhieuNhap := 'PN' || LPAD(SEQ_PN.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PTNCC_ID
BEFORE INSERT ON PHIEUTRANCC
FOR EACH ROW
BEGIN
    IF :NEW.MaPhieuTraNCC IS NULL THEN
        :NEW.MaPhieuTraNCC := 'TN' || LPAD(SEQ_PTNCC.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_TL_ID
BEFORE INSERT ON THANHLY
FOR EACH ROW
BEGIN
    IF :NEW.MaThanhLy IS NULL THEN
        :NEW.MaThanhLy := 'TL' || LPAD(SEQ_TL.NEXTVAL, 6, '0');
    END IF;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_SACH_DANG_MUON(P_MA_DOCGIA IN VARCHAR2)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT NVL(SUM(CT.SoLuong), 0)
    INTO V_COUNT
    FROM PHIEUMUON PM
    JOIN CT_PHIEUMUON CT ON CT.MaPhieuMuon = PM.MaPhieuMuon
    WHERE PM.MaDocGia = P_MA_DOCGIA
      AND PM.TrangThai IN ('DANG_MUON', 'QUA_HAN');

    RETURN V_COUNT;
END;
/

CREATE OR REPLACE FUNCTION FN_SO_LUONG_CON_LAI(P_MA_SACH IN VARCHAR2)
RETURN NUMBER
IS
    V_SO_LUONG NUMBER;
BEGIN
    SELECT SoLuongCon
    INTO V_SO_LUONG
    FROM KHOSACH
    WHERE MaSach = P_MA_SACH;

    RETURN V_SO_LUONG;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_KIEM_TRA_THE_HOP_LE(P_MA_DOCGIA IN VARCHAR2)
RETURN NUMBER
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_COUNT
    FROM DOCGIA
    WHERE MaDocGia = P_MA_DOCGIA
      AND TrangThai = 'HOAT_DONG'
      AND (NgayHetHan IS NULL OR NgayHetHan >= TRUNC(SYSDATE));

    RETURN CASE WHEN V_COUNT = 1 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE FUNCTION FN_TINH_TIEN_PHAT(P_MA_PHIEUMUON IN VARCHAR2)
RETURN NUMBER
IS
    V_NGAY_HEN_TRA DATE;
    V_SO_NGAY_TRE NUMBER;
BEGIN
    SELECT NgayHenTra
    INTO V_NGAY_HEN_TRA
    FROM PHIEUMUON
    WHERE MaPhieuMuon = P_MA_PHIEUMUON;

    V_SO_NGAY_TRE := GREATEST(TRUNC(SYSDATE) - TRUNC(V_NGAY_HEN_TRA), 0);
    RETURN V_SO_NGAY_TRE * 1000;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

CREATE OR REPLACE PROCEDURE SP_DANGKY_DOCGIA(
    P_TEN_DANG_NHAP IN VARCHAR2,
    P_MAT_KHAU      IN VARCHAR2,
    P_HO_TEN        IN VARCHAR2,
    P_EMAIL         IN VARCHAR2,
    P_SO_DIEN_THOAI IN VARCHAR2,
    P_DIA_CHI       IN VARCHAR2,
    P_NGAY_HET_HAN  IN DATE DEFAULT NULL
)
IS
    V_MA_TAI_KHOAN TAIKHOAN.MaTaiKhoan%TYPE;
BEGIN
    INSERT INTO TAIKHOAN(TenDangNhap, MatKhau, VaiTro)
    VALUES (P_TEN_DANG_NHAP, P_MAT_KHAU, 'DOC_GIA')
    RETURNING MaTaiKhoan INTO V_MA_TAI_KHOAN;

    INSERT INTO DOCGIA(MaTaiKhoan, HoTen, Email, SoDienThoai, DiaChi, NgayHetHan)
    VALUES (V_MA_TAI_KHOAN, P_HO_TEN, P_EMAIL, P_SO_DIEN_THOAI, P_DIA_CHI, P_NGAY_HET_HAN);
END;
/

CREATE OR REPLACE PROCEDURE SP_TAO_PHIEU_MUON(
    P_MA_DOCGIA   IN VARCHAR2,
    P_MA_NHANVIEN IN VARCHAR2,
    P_NGAY_HEN_TRA IN DATE,
    P_MA_PHIEU_MUON OUT VARCHAR2
)
IS
BEGIN
    IF FN_KIEM_TRA_THE_HOP_LE(P_MA_DOCGIA) = 0 THEN
        RAISE_APPLICATION_ERROR(-20101, 'Thẻ độc giả không hợp lệ hoặc đã hết hạn.');
    END IF;

    INSERT INTO PHIEUMUON(MaDocGia, MaNhanVien, NgayMuon, NgayHenTra, TrangThai)
    VALUES (P_MA_DOCGIA, P_MA_NHANVIEN, SYSDATE, P_NGAY_HEN_TRA, 'DANG_MUON')
    RETURNING MaPhieuMuon INTO P_MA_PHIEU_MUON;
END;
/

CREATE OR REPLACE PROCEDURE SP_THEM_CT_PHIEUMUON(
    P_MA_PHIEU_MUON IN VARCHAR2,
    P_MA_SACH       IN VARCHAR2,
    P_SO_LUONG      IN NUMBER DEFAULT 1
)
IS
    V_SO_LUONG_CON NUMBER;
BEGIN
    SELECT SoLuongCon
    INTO V_SO_LUONG_CON
    FROM KHOSACH
    WHERE MaSach = P_MA_SACH
    FOR UPDATE;

    IF P_SO_LUONG <= 0 THEN
        RAISE_APPLICATION_ERROR(-20102, 'Số lượng mượn phải lớn hơn 0.');
    END IF;

    IF V_SO_LUONG_CON < P_SO_LUONG THEN
        RAISE_APPLICATION_ERROR(-20103, 'Không đủ số lượng sách còn trong kho.');
    END IF;

    INSERT INTO CT_PHIEUMUON(MaPhieuMuon, MaSach, SoLuong)
    VALUES (P_MA_PHIEU_MUON, P_MA_SACH, P_SO_LUONG);

    UPDATE KHOSACH
    SET SoLuongCon = SoLuongCon - P_SO_LUONG
    WHERE MaSach = P_MA_SACH;
END;
/

CREATE OR REPLACE PROCEDURE SP_TRA_SACH(
    P_MA_PHIEU_MUON IN VARCHAR2,
    P_MA_NHANVIEN   IN VARCHAR2
)
IS
    V_TIEN_PHAT NUMBER;
    V_TRANG_THAI PHIEUMUON.TrangThai%TYPE;
BEGIN
    SELECT TrangThai
    INTO V_TRANG_THAI
    FROM PHIEUMUON
    WHERE MaPhieuMuon = P_MA_PHIEU_MUON
    FOR UPDATE;

    IF V_TRANG_THAI = 'DA_TRA' THEN
        RAISE_APPLICATION_ERROR(-20108, 'Phieu muon da duoc tra truoc do.');
    END IF;

    IF V_TRANG_THAI = 'HUY' THEN
        RAISE_APPLICATION_ERROR(-20109, 'Khong the tra phieu muon da huy.');
    END IF;

    INSERT INTO PHIEUTRA(MaPhieuMuon, MaNhanVien, NgayTra)
    VALUES (P_MA_PHIEU_MUON, P_MA_NHANVIEN, SYSDATE);

    UPDATE KHOSACH KS
    SET KS.SoLuongCon = KS.SoLuongCon + (
        SELECT NVL(SUM(CT.SoLuong), 0)
        FROM CT_PHIEUMUON CT
        WHERE CT.MaPhieuMuon = P_MA_PHIEU_MUON
          AND CT.MaSach = KS.MaSach
          AND CT.TrangThai = 'DANG_MUON'
    )
    WHERE EXISTS (
        SELECT 1
        FROM CT_PHIEUMUON CT
        WHERE CT.MaPhieuMuon = P_MA_PHIEU_MUON
          AND CT.MaSach = KS.MaSach
          AND CT.TrangThai = 'DANG_MUON'
    );

    UPDATE CT_PHIEUMUON
    SET TrangThai = 'DA_TRA'
    WHERE MaPhieuMuon = P_MA_PHIEU_MUON
      AND TrangThai = 'DANG_MUON';

    V_TIEN_PHAT := FN_TINH_TIEN_PHAT(P_MA_PHIEU_MUON);

    IF V_TIEN_PHAT > 0 THEN
        INSERT INTO VIPHAM(MaPhieuMuon, LoaiViPham, TienPhat)
        VALUES (P_MA_PHIEU_MUON, 'QUA_HAN', V_TIEN_PHAT);
    END IF;

    UPDATE PHIEUMUON SET TrangThai = 'DA_TRA' WHERE MaPhieuMuon = P_MA_PHIEU_MUON;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20110, 'Khong tim thay phieu muon.');
END;
/

CREATE OR REPLACE PROCEDURE SP_NHAP_SACH(
    P_MA_NCC       IN VARCHAR2,
    P_MA_NHANVIEN  IN VARCHAR2,
    P_MA_SACH      IN VARCHAR2,
    P_SO_LUONG     IN NUMBER,
    P_DON_GIA      IN NUMBER
)
IS
    V_MA_PHIEU_NHAP PHIEUNHAP.MaPhieuNhap%TYPE;
    V_HAS_KHO       NUMBER;
BEGIN
    IF P_SO_LUONG <= 0 THEN
        RAISE_APPLICATION_ERROR(-20104, 'Số lượng nhập phải lớn hơn 0.');
    END IF;

    INSERT INTO PHIEUNHAP(MaNhaCungCap, MaNhanVien, NgayNhap, TongTien)
    VALUES (P_MA_NCC, P_MA_NHANVIEN, SYSDATE, P_SO_LUONG * P_DON_GIA)
    RETURNING MaPhieuNhap INTO V_MA_PHIEU_NHAP;

    INSERT INTO CT_PHIEUNHAP(MaPhieuNhap, MaSach, SoLuong, DonGia)
    VALUES (V_MA_PHIEU_NHAP, P_MA_SACH, P_SO_LUONG, P_DON_GIA);

    INSERT INTO LOSACH(MaSach, MaNhaCungCap, NgayNhap, DonGia, SoLuongNhap)
    VALUES (P_MA_SACH, P_MA_NCC, SYSDATE, P_DON_GIA, P_SO_LUONG);

    BEGIN
        SELECT 1
        INTO V_HAS_KHO
        FROM KHOSACH
        WHERE MaSach = P_MA_SACH
        FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_HAS_KHO := 0;
    END;

    IF V_HAS_KHO = 0 THEN
        INSERT INTO KHOSACH(MaSach, SoLuongTong, SoLuongCon, SoLuongHong)
        VALUES (P_MA_SACH, P_SO_LUONG, P_SO_LUONG, 0);
    ELSE
        UPDATE KHOSACH
        SET SoLuongTong = SoLuongTong + P_SO_LUONG,
            SoLuongCon = SoLuongCon + P_SO_LUONG
        WHERE MaSach = P_MA_SACH;
    END IF;
END;
/


CREATE OR REPLACE PROCEDURE SP_THANHLY_SACH(
    P_MA_SACH      IN VARCHAR2,
    P_MA_NHANVIEN  IN VARCHAR2,
    P_SO_LUONG     IN NUMBER,
    P_LY_DO        IN VARCHAR2
)
IS
    V_SO_LUONG_CON KHOSACH.SoLuongCon%TYPE;
BEGIN
    IF P_SO_LUONG <= 0 THEN
        RAISE_APPLICATION_ERROR(-20105, 'So luong thanh ly phai lon hon 0.');
    END IF;

    SELECT SoLuongCon
    INTO V_SO_LUONG_CON
    FROM KHOSACH
    WHERE MaSach = P_MA_SACH
    FOR UPDATE;

    IF V_SO_LUONG_CON < P_SO_LUONG THEN
        RAISE_APPLICATION_ERROR(-20106, 'So luong thanh ly vuot qua so luong kha dung.');
    END IF;

    INSERT INTO THANHLY(MaSach, MaNhanVien, SoLuong, LyDo)
    VALUES (P_MA_SACH, P_MA_NHANVIEN, P_SO_LUONG, P_LY_DO);

    UPDATE KHOSACH
    SET SoLuongTong = SoLuongTong - P_SO_LUONG,
        SoLuongCon = SoLuongCon - P_SO_LUONG
    WHERE MaSach = P_MA_SACH;

    UPDATE SACH
    SET TrangThai = 'NGUNG_LUU_THONG'
    WHERE MaSach = P_MA_SACH
      AND NOT EXISTS (
          SELECT 1 FROM KHOSACH WHERE MaSach = P_MA_SACH AND SoLuongTong > 0
      );
END;
/

CREATE OR REPLACE TRIGGER TRG_CAPNHAT_QUA_HAN
BEFORE UPDATE ON PHIEUMUON
FOR EACH ROW
BEGIN
    IF :NEW.TrangThai = 'DANG_MUON' AND :NEW.NgayHenTra < TRUNC(SYSDATE) THEN
        :NEW.TrangThai := 'QUA_HAN';
    END IF;
END;
/
